---
deployment:
  tasks:
    - export NVM_DIR=$HOME/.nvm
    - source $NVM_DIR/nvm.sh
    - nvm use 20.19.0
    - npx npm@10 ci
    - npx npm@10 run build
    - rsync -a --delete .next/ $HOME/apps/crm-ddm/.next/
    - mkdir -p $HOME/apps/crm-ddm/tmp && touch $HOME/apps/crm-ddm/tmp/restart.txt